### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'toggleViewAction'

### ISSUE THREAD

**Issue by alexcg1** [triplus/Glass#11]
Just installed Glass on FreeCAD 0.20.2 on Arch Linux and having this issue. Transparency isn't happening and Report view is showing errors

![image](https://user-images.githubusercontent.com/4182659/224381207-4deee1fb-d062-42cf-9388-d6d1c26010cf.png)

Here's the error message:

```
18:16:05  Traceback (most recent call last):
18:16:05    File "/home/alexcg/.local/share/FreeCAD/Mod/Glass/GlassGui.py", line 211, in onStart
18:16:05      setMode() # activate Glass mode
18:16:05    File "/home/alexcg/.local/share/FreeCAD/Mod/Glass/GlassGui.py", line 163, in setMode
18:16:05      dock.setParent(mdi)
18:16:05  AttributeError: 'NoneType' object has no attribute 'setParent'
```

**Comment by darrellenns** [comment]
Check your setting for Edit->Preferences->General->Tree view mode. I ran into this and found that it works if that is set to "Both".
